#!/bin/bash

set -- -nostdlib $(echo "$@" | sed 's/-Wl,[^ ]*//g')

if [[ "$@" == *" -shared "* ]] || [[ "$@" == *" -c "* ]]; then
    set -- $(echo "$@" | sed 's/-fvisibility=hidden//')
    gcc "$@"
else
    set -- $(echo "$@" | sed 's/\.\/\.libs\/libarchive\.so/-L.\/.libs -larchive/')
    gcc -Wl,-T link.ld $@
fi
