/*
 * This file was generated by the mkbuiltins program.
 */

#define COMMANDCMD (builtincmd + 7)
#define EVALCMD    (builtincmd + 10)
#define EXECCMD    (builtincmd + 11)

#define NUMBUILTINS 36

#define BUILTIN_SPECIAL 0x1
#define BUILTIN_REGULAR 0x2
#define BUILTIN_ASSIGN  0x4

struct builtincmd {
	const char *name;
	int (*builtin)(int, char **);
	unsigned flags;
};

extern const struct builtincmd builtincmd[];
