#!/bin/bash

if [[ "$@" == *"-shared"* ]] || [[ "$@" == *"-c"* ]] || [[ "$@" == *"-E"* ]]; then
    g++ -nostdinc "$@" -I $profan_path/include/zlibs
else
    g++ -nostdinc -Wl,-T $profan_path/tools/link_elf.ld "$@" -I $profan_path/include/zlibs
fi
