#!/bin/python3

import os
import sys

nargs = []

i = 1
while i < len(sys.argv):    
    if sys.argv[i].startswith("--sysroot"):
        i += 1
    elif sys.argv[i] == "-I" and "profan" in sys.argv[i+1]:
        i += 2
    else:
        nargs.append(sys.argv[i])
        i += 1

os.execvp(nargs[0], nargs)
