FLAG1="-fPIC -march=i386 -m32 -fno-builtin -fno-stack-protector \
-std=c99 -Wall -I. -I ld80 -I include -I src -I i387 -I ../../profanOS/include/zlibs/ \
-DASSEMBLER -D__BSD_VISIBLE -nostdlib -nostdinc -Wno-unused-function"

FALG2="-march=i386 -m32 -I. -I include -I i387 -I src -I ld80 \
-DASSEMBLER -D__BSD_VISIBLE -nostdlib -nostdinc -fno-builtin -fno-stack-protector"

DEST="../../build"

gcc $FLAG1 -c src/common.c -o src/common.c.o
gcc $FLAG1 -c src/e_acos.c -o src/e_acos.c.o
gcc $FLAG1 -c src/e_acosf.c -o src/e_acosf.c.o
gcc $FLAG1 -c src/e_acosh.c -o src/e_acosh.c.o
gcc $FLAG1 -c src/e_acoshf.c -o src/e_acoshf.c.o
gcc $FLAG1 -c src/e_asin.c -o src/e_asin.c.o
gcc $FLAG1 -c src/e_asinf.c -o src/e_asinf.c.o
gcc $FLAG1 -c src/e_atan2.c -o src/e_atan2.c.o
gcc $FLAG1 -c src/e_atan2f.c -o src/e_atan2f.c.o
gcc $FLAG1 -c src/e_atanh.c -o src/e_atanh.c.o
gcc $FLAG1 -c src/e_atanhf.c -o src/e_atanhf.c.o
gcc $FLAG1 -c src/e_cosh.c -o src/e_cosh.c.o
gcc $FLAG1 -c src/e_coshf.c -o src/e_coshf.c.o
gcc $FLAG1 -c src/e_expf.c -o src/e_expf.c.o
gcc $FLAG1 -c src/e_fmodf.c -o src/e_fmodf.c.o
gcc $FLAG1 -c src/e_hypot.c -o src/e_hypot.c.o
gcc $FLAG1 -c src/e_hypotf.c -o src/e_hypotf.c.o
gcc $FLAG1 -c src/e_j0.c -o src/e_j0.c.o
gcc $FLAG1 -c src/e_j0f.c -o src/e_j0f.c.o
gcc $FLAG1 -c src/e_j1.c -o src/e_j1.c.o
gcc $FLAG1 -c src/e_j1f.c -o src/e_j1f.c.o
gcc $FLAG1 -c src/e_jn.c -o src/e_jn.c.o
gcc $FLAG1 -c src/e_jnf.c -o src/e_jnf.c.o
gcc $FLAG1 -c src/e_lgamma.c -o src/e_lgamma.c.o
gcc $FLAG1 -c src/e_lgamma_r.c -o src/e_lgamma_r.c.o
gcc $FLAG1 -c src/e_lgammaf.c -o src/e_lgammaf.c.o
gcc $FLAG1 -c src/e_lgammaf_r.c -o src/e_lgammaf_r.c.o
gcc $FLAG1 -c src/e_log2.c -o src/e_log2.c.o
gcc $FLAG1 -c src/e_log2f.c -o src/e_log2f.c.o
gcc $FLAG1 -c src/e_pow.c -o src/e_pow.c.o
gcc $FLAG1 -c src/e_powf.c -o src/e_powf.c.o
gcc $FLAG1 -c src/e_rem_pio2.c -o src/e_rem_pio2.c.o
gcc $FLAG1 -c src/e_rem_pio2f.c -o src/e_rem_pio2f.c.o
gcc $FLAG1 -c src/e_sinh.c -o src/e_sinh.c.o
gcc $FLAG1 -c src/e_sinhf.c -o src/e_sinhf.c.o
gcc $FLAG1 -c src/k_cos.c -o src/k_cos.c.o
gcc $FLAG1 -c src/k_exp.c -o src/k_exp.c.o
gcc $FLAG1 -c src/k_expf.c -o src/k_expf.c.o
gcc $FLAG1 -c src/k_rem_pio2.c -o src/k_rem_pio2.c.o
gcc $FLAG1 -c src/k_sin.c -o src/k_sin.c.o
gcc $FLAG1 -c src/k_tan.c -o src/k_tan.c.o
gcc $FLAG1 -c src/k_cosf.c -o src/k_cosf.c.o
gcc $FLAG1 -c src/k_sinf.c -o src/k_sinf.c.o
gcc $FLAG1 -c src/k_tanf.c -o src/k_tanf.c.o
gcc $FLAG1 -c src/s_asinh.c -o src/s_asinh.c.o
gcc $FLAG1 -c src/s_asinhf.c -o src/s_asinhf.c.o
gcc $FLAG1 -c src/s_atan.c -o src/s_atan.c.o
gcc $FLAG1 -c src/s_atanf.c -o src/s_atanf.c.o
gcc $FLAG1 -c src/s_carg.c -o src/s_carg.c.o
gcc $FLAG1 -c src/s_cargf.c -o src/s_cargf.c.o
gcc $FLAG1 -c src/s_cbrt.c -o src/s_cbrt.c.o
gcc $FLAG1 -c src/s_cbrtf.c -o src/s_cbrtf.c.o
gcc $FLAG1 -c src/s_cos.c -o src/s_cos.c.o
gcc $FLAG1 -c src/s_cosf.c -o src/s_cosf.c.o
gcc $FLAG1 -c src/s_csqrt.c -o src/s_csqrt.c.o
gcc $FLAG1 -c src/s_csqrtf.c -o src/s_csqrtf.c.o
gcc $FLAG1 -c src/s_erf.c -o src/s_erf.c.o
gcc $FLAG1 -c src/s_erff.c -o src/s_erff.c.o
gcc $FLAG1 -c src/s_exp2.c -o src/s_exp2.c.o
gcc $FLAG1 -c src/s_exp2f.c -o src/s_exp2f.c.o
gcc $FLAG1 -c src/s_expm1.c -o src/s_expm1.c.o
gcc $FLAG1 -c src/s_expm1f.c -o src/s_expm1f.c.o
gcc $FLAG1 -c src/s_fabs.c -o src/s_fabs.c.o
gcc $FLAG1 -c src/s_fabsf.c -o src/s_fabsf.c.o
gcc $FLAG1 -c src/s_fdim.c -o src/s_fdim.c.o
gcc $FLAG1 -c src/s_fmax.c -o src/s_fmax.c.o
gcc $FLAG1 -c src/s_fmaxf.c -o src/s_fmaxf.c.o
gcc $FLAG1 -c src/s_fmin.c -o src/s_fmin.c.o
gcc $FLAG1 -c src/s_fminf.c -o src/s_fminf.c.o
gcc $FLAG1 -c src/s_fpclassify.c -o src/s_fpclassify.c.o
gcc $FLAG1 -c src/s_frexp.c -o src/s_frexp.c.o
gcc $FLAG1 -c src/s_frexpf.c -o src/s_frexpf.c.o
gcc $FLAG1 -c src/s_ilogb.c -o src/s_ilogb.c.o
gcc $FLAG1 -c src/s_ilogbf.c -o src/s_ilogbf.c.o
gcc $FLAG1 -c src/s_isinf.c -o src/s_isinf.c.o
gcc $FLAG1 -c src/s_isfinite.c -o src/s_isfinite.c.o
gcc $FLAG1 -c src/s_isnormal.c -o src/s_isnormal.c.o
gcc $FLAG1 -c src/s_isnan.c -o src/s_isnan.c.o
gcc $FLAG1 -c src/s_log1p.c -o src/s_log1p.c.o
gcc $FLAG1 -c src/s_log1pf.c -o src/s_log1pf.c.o
gcc $FLAG1 -c src/s_modf.c -o src/s_modf.c.o
gcc $FLAG1 -c src/s_modff.c -o src/s_modff.c.o
gcc $FLAG1 -c src/s_nextafter.c -o src/s_nextafter.c.o
gcc $FLAG1 -c src/s_nextafterf.c -o src/s_nextafterf.c.o
gcc $FLAG1 -c src/s_nexttowardf.c -o src/s_nexttowardf.c.o
gcc $FLAG1 -c src/s_round.c -o src/s_round.c.o
gcc $FLAG1 -c src/s_roundf.c -o src/s_roundf.c.o
gcc $FLAG1 -c src/s_scalbln.c -o src/s_scalbln.c.o
gcc $FLAG1 -c src/s_signbit.c -o src/s_signbit.c.o
gcc $FLAG1 -c src/s_signgam.c -o src/s_signgam.c.o
gcc $FLAG1 -c src/s_sin.c -o src/s_sin.c.o
gcc $FLAG1 -c src/s_sincos.c -o src/s_sincos.c.o
gcc $FLAG1 -c src/s_sinf.c -o src/s_sinf.c.o
gcc $FLAG1 -c src/s_sincosf.c -o src/s_sincosf.c.o
gcc $FLAG1 -c src/s_tanf.c -o src/s_tanf.c.o
gcc $FLAG1 -c src/s_tanh.c -o src/s_tanh.c.o
gcc $FLAG1 -c src/s_tanhf.c -o src/s_tanhf.c.o
gcc $FLAG1 -c src/s_tgammaf.c -o src/s_tgammaf.c.o
gcc $FLAG1 -c src/s_cpow.c -o src/s_cpow.c.o
gcc $FLAG1 -c src/s_cpowf.c -o src/s_cpowf.c.o
gcc $FLAG1 -c src/w_cabs.c -o src/w_cabs.c.o
gcc $FLAG1 -c src/w_cabsf.c -o src/w_cabsf.c.o
gcc $FLAG1 -c src/s_fma.c -o src/s_fma.c.o
gcc $FLAG1 -c src/s_fmaf.c -o src/s_fmaf.c.o
gcc $FLAG1 -c src/s_lround.c -o src/s_lround.c.o
gcc $FLAG1 -c src/s_lroundf.c -o src/s_lroundf.c.o
gcc $FLAG1 -c src/s_llround.c -o src/s_llround.c.o
gcc $FLAG1 -c src/s_llroundf.c -o src/s_llroundf.c.o
gcc $FLAG1 -c src/s_nearbyint.c -o src/s_nearbyint.c.o
gcc $FLAG1 -c src/s_nan.c -o src/s_nan.c.o
gcc $FLAG1 -c src/s_fabsl.c -o src/s_fabsl.c.o
gcc $FLAG1 -c src/s_modfl.c -o src/s_modfl.c.o
gcc $FLAG1 -c src/e_acosl.c -o src/e_acosl.c.o
gcc $FLAG1 -c src/e_asinl.c -o src/e_asinl.c.o
gcc $FLAG1 -c src/e_atan2l.c -o src/e_atan2l.c.o
gcc $FLAG1 -c src/e_fmodl.c -o src/e_fmodl.c.o
gcc $FLAG1 -c src/s_fmaxl.c -o src/s_fmaxl.c.o
gcc $FLAG1 -c src/s_fminl.c -o src/s_fminl.c.o
gcc $FLAG1 -c src/s_ilogbl.c -o src/s_ilogbl.c.o
gcc $FLAG1 -c src/e_hypotl.c -o src/e_hypotl.c.o
gcc $FLAG1 -c src/e_lgammal.c -o src/e_lgammal.c.o
gcc $FLAG1 -c src/s_atanl.c -o src/s_atanl.c.o
gcc $FLAG1 -c src/s_cosl.c -o src/s_cosl.c.o
gcc $FLAG1 -c src/s_cprojl.c -o src/s_cprojl.c.o
gcc $FLAG1 -c src/s_csqrtl.c -o src/s_csqrtl.c.o
gcc $FLAG1 -c src/s_fmal.c -o src/s_fmal.c.o
gcc $FLAG1 -c src/s_frexpl.c -o src/s_frexpl.c.o
gcc $FLAG1 -c src/s_nexttoward.c -o src/s_nexttoward.c.o
gcc $FLAG1 -c src/s_roundl.c -o src/s_roundl.c.o
gcc $FLAG1 -c src/s_lroundl.c -o src/s_lroundl.c.o
gcc $FLAG1 -c src/s_llroundl.c -o src/s_llroundl.c.o
gcc $FLAG1 -c src/s_cpowl.c -o src/s_cpowl.c.o
gcc $FLAG1 -c src/s_cargl.c -o src/s_cargl.c.o
gcc $FLAG1 -c src/s_sinl.c -o src/s_sinl.c.o
gcc $FLAG1 -c src/s_sincosl.c -o src/s_sincosl.c.o
gcc $FLAG1 -c src/s_tanl.c -o src/s_tanl.c.o
gcc $FLAG1 -c src/w_cabsl.c -o src/w_cabsl.c.o
gcc $FLAG1 -c src/s_nextafterl.c -o src/s_nextafterl.c.o
gcc $FLAG1 -c src/polevll.c -o src/polevll.c.o
gcc $FLAG1 -c src/s_casinl.c -o src/s_casinl.c.o
gcc $FLAG1 -c src/s_ctanl.c -o src/s_ctanl.c.o
gcc $FLAG1 -c src/s_cimagl.c -o src/s_cimagl.c.o
gcc $FLAG1 -c src/s_conjl.c -o src/s_conjl.c.o
gcc $FLAG1 -c src/s_creall.c -o src/s_creall.c.o
gcc $FLAG1 -c src/s_cacoshl.c -o src/s_cacoshl.c.o
gcc $FLAG1 -c src/s_catanhl.c -o src/s_catanhl.c.o
gcc $FLAG1 -c src/s_casinhl.c -o src/s_casinhl.c.o
gcc $FLAG1 -c src/s_catanl.c -o src/s_catanl.c.o
gcc $FLAG1 -c src/s_csinl.c -o src/s_csinl.c.o
gcc $FLAG1 -c src/s_cacosl.c -o src/s_cacosl.c.o
gcc $FLAG1 -c src/s_cexpl.c -o src/s_cexpl.c.o
gcc $FLAG1 -c src/s_csinhl.c -o src/s_csinhl.c.o
gcc $FLAG1 -c src/s_ccoshl.c -o src/s_ccoshl.c.o
gcc $FLAG1 -c src/s_clogl.c -o src/s_clogl.c.o
gcc $FLAG1 -c src/s_ctanhl.c -o src/s_ctanhl.c.o
gcc $FLAG1 -c src/s_ccosl.c -o src/s_ccosl.c.o
gcc $FLAG1 -c src/s_cbrtl.c -o src/s_cbrtl.c.o
gcc $FLAG1 -c src/s_ccosh.c -o src/s_ccosh.c.o
gcc $FLAG1 -c src/s_ccoshf.c -o src/s_ccoshf.c.o
gcc $FLAG1 -c src/s_cexp.c -o src/s_cexp.c.o
gcc $FLAG1 -c src/s_cexpf.c -o src/s_cexpf.c.o
gcc $FLAG1 -c src/s_cimag.c -o src/s_cimag.c.o
gcc $FLAG1 -c src/s_cimagf.c -o src/s_cimagf.c.o
gcc $FLAG1 -c src/s_conj.c -o src/s_conj.c.o
gcc $FLAG1 -c src/s_conjf.c -o src/s_conjf.c.o
gcc $FLAG1 -c src/s_cproj.c -o src/s_cproj.c.o
gcc $FLAG1 -c src/s_cprojf.c -o src/s_cprojf.c.o
gcc $FLAG1 -c src/s_creal.c -o src/s_creal.c.o
gcc $FLAG1 -c src/s_crealf.c -o src/s_crealf.c.o
gcc $FLAG1 -c src/s_csinh.c -o src/s_csinh.c.o
gcc $FLAG1 -c src/s_csinhf.c -o src/s_csinhf.c.o
gcc $FLAG1 -c src/s_ctanh.c -o src/s_ctanh.c.o
gcc $FLAG1 -c src/s_ctanhf.c -o src/s_ctanhf.c.o
gcc $FLAG1 -c src/s_cacos.c -o src/s_cacos.c.o
gcc $FLAG1 -c src/s_cacosf.c -o src/s_cacosf.c.o
gcc $FLAG1 -c src/s_cacosh.c -o src/s_cacosh.c.o
gcc $FLAG1 -c src/s_cacoshf.c -o src/s_cacoshf.c.o
gcc $FLAG1 -c src/s_casin.c -o src/s_casin.c.o
gcc $FLAG1 -c src/s_casinf.c -o src/s_casinf.c.o
gcc $FLAG1 -c src/s_casinh.c -o src/s_casinh.c.o
gcc $FLAG1 -c src/s_casinhf.c -o src/s_casinhf.c.o
gcc $FLAG1 -c src/s_catan.c -o src/s_catan.c.o
gcc $FLAG1 -c src/s_catanf.c -o src/s_catanf.c.o
gcc $FLAG1 -c src/s_catanh.c -o src/s_catanh.c.o
gcc $FLAG1 -c src/s_catanhf.c -o src/s_catanhf.c.o
gcc $FLAG1 -c src/s_clog.c -o src/s_clog.c.o
gcc $FLAG1 -c src/s_clogf.c -o src/s_clogf.c.o

gcc $FALG2 -c i387/e_exp.S -o i387/e_exp.S.o
gcc $FALG2 -c i387/e_fmod.S -o i387/e_fmod.S.o
gcc $FALG2 -c i387/e_log.S -o i387/e_log.S.o
gcc $FALG2 -c i387/e_log10.S -o i387/e_log10.S.o
gcc $FALG2 -c i387/e_remainder.S -o i387/e_remainder.S.o
gcc $FALG2 -c i387/e_sqrt.S -o i387/e_sqrt.S.o
gcc $FALG2 -c i387/s_ceil.S -o i387/s_ceil.S.o
gcc $FALG2 -c i387/s_copysign.S -o i387/s_copysign.S.o
gcc $FALG2 -c i387/s_floor.S -o i387/s_floor.S.o
gcc $FALG2 -c i387/s_llrint.S -o i387/s_llrint.S.o
gcc $FALG2 -c i387/s_logb.S -o i387/s_logb.S.o
gcc $FALG2 -c i387/s_lrint.S -o i387/s_lrint.S.o
gcc $FALG2 -c i387/s_remquo.S -o i387/s_remquo.S.o
gcc $FALG2 -c i387/s_rint.S -o i387/s_rint.S.o
gcc $FALG2 -c i387/s_tan.S -o i387/s_tan.S.o
gcc $FALG2 -c i387/s_trunc.S -o i387/s_trunc.S.o
gcc $FALG2 -c i387/s_scalbn.S -o i387/s_scalbn.S.o
gcc $FALG2 -c i387/s_scalbnf.S -o i387/s_scalbnf.S.o
gcc $FALG2 -c i387/s_scalbnl.S -o i387/s_scalbnl.S.o
gcc $FALG2 -c i387/e_log10f.S -o i387/e_log10f.S.o
gcc $FALG2 -c i387/e_logf.S -o i387/e_logf.S.o
gcc $FALG2 -c i387/e_remainderf.S -o i387/e_remainderf.S.o
gcc $FALG2 -c i387/e_sqrtf.S -o i387/e_sqrtf.S.o
gcc $FALG2 -c i387/s_ceilf.S -o i387/s_ceilf.S.o
gcc $FALG2 -c i387/s_copysignf.S -o i387/s_copysignf.S.o
gcc $FALG2 -c i387/s_floorf.S -o i387/s_floorf.S.o
gcc $FALG2 -c i387/s_llrintf.S -o i387/s_llrintf.S.o
gcc $FALG2 -c i387/s_logbf.S -o i387/s_logbf.S.o
gcc $FALG2 -c i387/s_lrintf.S -o i387/s_lrintf.S.o
gcc $FALG2 -c i387/s_remquof.S -o i387/s_remquof.S.o
gcc $FALG2 -c i387/s_rintf.S -o i387/s_rintf.S.o
gcc $FALG2 -c i387/s_truncf.S -o i387/s_truncf.S.o
gcc $FALG2 -c i387/e_remainderl.S -o i387/e_remainderl.S.o
gcc $FALG2 -c i387/e_sqrtl.S -o i387/e_sqrtl.S.o
gcc $FALG2 -c i387/s_ceill.S -o i387/s_ceill.S.o
gcc $FALG2 -c i387/s_copysignl.S -o i387/s_copysignl.S.o
gcc $FALG2 -c i387/s_floorl.S -o i387/s_floorl.S.o
gcc $FALG2 -c i387/s_llrintl.S -o i387/s_llrintl.S.o
gcc $FALG2 -c i387/s_logbl.S -o i387/s_logbl.S.o
gcc $FALG2 -c i387/s_lrintl.S -o i387/s_lrintl.S.o
gcc $FALG2 -c i387/s_remquol.S -o i387/s_remquol.S.o
gcc $FALG2 -c i387/s_rintl.S -o i387/s_rintl.S.o
gcc $FALG2 -c i387/s_truncl.S -o i387/s_truncl.S.o
gcc $FLAG1 -c i387/fenv.c -o i387/fenv.c.o

gcc $FLAG1 -c bsdsrc/b_exp.c -o bsdsrc/b_exp.c.o
gcc $FLAG1 -c bsdsrc/b_log.c -o bsdsrc/b_log.c.o
gcc $FLAG1 -c bsdsrc/b_tgamma.c -o bsdsrc/b_tgamma.c.o

gcc $FLAG1 -c ld80/invtrig.c -o ld80/invtrig.c.o
gcc $FLAG1 -c ld80/e_acoshl.c -o ld80/e_acoshl.c.o
gcc $FLAG1 -c ld80/e_powl.c -o ld80/e_powl.c.o
gcc $FLAG1 -c ld80/k_tanl.c -o ld80/k_tanl.c.o
gcc $FLAG1 -c ld80/s_exp2l.c -o ld80/s_exp2l.c.o
gcc $FLAG1 -c ld80/e_atanhl.c -o ld80/e_atanhl.c.o
gcc $FLAG1 -c ld80/e_lgammal_r.c -o ld80/e_lgammal_r.c.o
gcc $FLAG1 -c ld80/e_sinhl.c -o ld80/e_sinhl.c.o
gcc $FLAG1 -c ld80/s_asinhl.c -o ld80/s_asinhl.c.o
gcc $FLAG1 -c ld80/s_expm1l.c -o ld80/s_expm1l.c.o
gcc $FLAG1 -c ld80/e_coshl.c -o ld80/e_coshl.c.o
gcc $FLAG1 -c ld80/e_log10l.c -o ld80/e_log10l.c.o
gcc $FLAG1 -c ld80/e_tgammal.c -o ld80/e_tgammal.c.o
gcc $FLAG1 -c ld80/e_expl.c -o ld80/e_expl.c.o
gcc $FLAG1 -c ld80/e_log2l.c -o ld80/e_log2l.c.o
gcc $FLAG1 -c ld80/k_cosl.c -o ld80/k_cosl.c.o
gcc $FLAG1 -c ld80/s_log1pl.c -o ld80/s_log1pl.c.o
gcc $FLAG1 -c ld80/s_tanhl.c -o ld80/s_tanhl.c.o
gcc $FLAG1 -c ld80/e_logl.c -o ld80/e_logl.c.o
gcc $FLAG1 -c ld80/k_sinl.c -o ld80/k_sinl.c.o
gcc $FLAG1 -c ld80/s_erfl.c -o ld80/s_erfl.c.o
gcc $FLAG1 -c ld80/s_nanl.c -o ld80/s_nanl.c.o

ar -rcs $DEST/libm.a src/common.c.o src/e_acos.c.o src/e_acosf.c.o src/e_acosh.c.o src/e_acoshf.c.o src/e_asin.c.o src/e_asinf.c.o src/e_atan2.c.o src/e_atan2f.c.o src/e_atanh.c.o src/e_atanhf.c.o src/e_cosh.c.o src/e_coshf.c.o src/e_expf.c.o src/e_fmodf.c.o src/e_hypot.c.o src/e_hypotf.c.o src/e_j0.c.o src/e_j0f.c.o src/e_j1.c.o src/e_j1f.c.o src/e_jn.c.o src/e_jnf.c.o src/e_lgamma.c.o src/e_lgamma_r.c.o src/e_lgammaf.c.o src/e_lgammaf_r.c.o src/e_log2.c.o src/e_log2f.c.o src/e_pow.c.o src/e_powf.c.o src/e_rem_pio2.c.o src/e_rem_pio2f.c.o src/e_sinh.c.o src/e_sinhf.c.o src/k_cos.c.o src/k_exp.c.o src/k_expf.c.o src/k_rem_pio2.c.o src/k_sin.c.o src/k_tan.c.o src/k_cosf.c.o src/k_sinf.c.o src/k_tanf.c.o src/s_asinh.c.o src/s_asinhf.c.o src/s_atan.c.o src/s_atanf.c.o src/s_carg.c.o src/s_cargf.c.o src/s_cbrt.c.o src/s_cbrtf.c.o src/s_cos.c.o src/s_cosf.c.o src/s_csqrt.c.o src/s_csqrtf.c.o src/s_erf.c.o src/s_erff.c.o src/s_exp2.c.o src/s_exp2f.c.o src/s_expm1.c.o src/s_expm1f.c.o src/s_fabs.c.o src/s_fabsf.c.o src/s_fdim.c.o src/s_fmax.c.o src/s_fmaxf.c.o src/s_fmin.c.o src/s_fminf.c.o src/s_fpclassify.c.o src/s_frexp.c.o src/s_frexpf.c.o src/s_ilogb.c.o src/s_ilogbf.c.o src/s_isinf.c.o src/s_isfinite.c.o src/s_isnormal.c.o src/s_isnan.c.o src/s_log1p.c.o src/s_log1pf.c.o src/s_modf.c.o src/s_modff.c.o src/s_nextafter.c.o src/s_nextafterf.c.o src/s_nexttowardf.c.o src/s_round.c.o src/s_roundf.c.o src/s_scalbln.c.o src/s_signbit.c.o src/s_signgam.c.o src/s_sin.c.o src/s_sincos.c.o src/s_sinf.c.o src/s_sincosf.c.o src/s_tanf.c.o src/s_tanh.c.o src/s_tanhf.c.o src/s_tgammaf.c.o src/s_cpow.c.o src/s_cpowf.c.o src/w_cabs.c.o src/w_cabsf.c.o src/s_fma.c.o src/s_fmaf.c.o src/s_lround.c.o src/s_lroundf.c.o src/s_llround.c.o src/s_llroundf.c.o src/s_nearbyint.c.o src/s_nan.c.o src/s_fabsl.c.o src/s_modfl.c.o src/e_acosl.c.o src/e_asinl.c.o src/e_atan2l.c.o src/e_fmodl.c.o src/s_fmaxl.c.o src/s_fminl.c.o src/s_ilogbl.c.o src/e_hypotl.c.o src/e_lgammal.c.o src/s_atanl.c.o src/s_cosl.c.o src/s_cprojl.c.o src/s_csqrtl.c.o src/s_fmal.c.o src/s_frexpl.c.o src/s_nexttoward.c.o src/s_roundl.c.o src/s_lroundl.c.o src/s_llroundl.c.o src/s_cpowl.c.o src/s_cargl.c.o src/s_sinl.c.o src/s_sincosl.c.o src/s_tanl.c.o src/w_cabsl.c.o src/s_nextafterl.c.o src/polevll.c.o src/s_casinl.c.o src/s_ctanl.c.o src/s_cimagl.c.o src/s_conjl.c.o src/s_creall.c.o src/s_cacoshl.c.o src/s_catanhl.c.o src/s_casinhl.c.o src/s_catanl.c.o src/s_csinl.c.o src/s_cacosl.c.o src/s_cexpl.c.o src/s_csinhl.c.o src/s_ccoshl.c.o src/s_clogl.c.o src/s_ctanhl.c.o src/s_ccosl.c.o src/s_cbrtl.c.o src/s_ccosh.c.o src/s_ccoshf.c.o src/s_cexp.c.o src/s_cexpf.c.o src/s_cimag.c.o src/s_cimagf.c.o src/s_conj.c.o src/s_conjf.c.o src/s_cproj.c.o src/s_cprojf.c.o src/s_creal.c.o src/s_crealf.c.o src/s_csinh.c.o src/s_csinhf.c.o src/s_ctanh.c.o src/s_ctanhf.c.o src/s_cacos.c.o src/s_cacosf.c.o src/s_cacosh.c.o src/s_cacoshf.c.o src/s_casin.c.o src/s_casinf.c.o src/s_casinh.c.o src/s_casinhf.c.o src/s_catan.c.o src/s_catanf.c.o src/s_catanh.c.o src/s_catanhf.c.o src/s_clog.c.o src/s_clogf.c.o i387/e_exp.S.o i387/e_fmod.S.o i387/e_log.S.o i387/e_log10.S.o i387/e_remainder.S.o i387/e_sqrt.S.o i387/s_ceil.S.o i387/s_copysign.S.o i387/s_floor.S.o i387/s_llrint.S.o i387/s_logb.S.o i387/s_lrint.S.o i387/s_remquo.S.o i387/s_rint.S.o i387/s_tan.S.o i387/s_trunc.S.o i387/s_scalbn.S.o i387/s_scalbnf.S.o i387/s_scalbnl.S.o i387/e_log10f.S.o i387/e_logf.S.o i387/e_remainderf.S.o i387/e_sqrtf.S.o i387/s_ceilf.S.o i387/s_copysignf.S.o i387/s_floorf.S.o i387/s_llrintf.S.o i387/s_logbf.S.o i387/s_lrintf.S.o i387/s_remquof.S.o i387/s_rintf.S.o i387/s_truncf.S.o i387/e_remainderl.S.o i387/e_sqrtl.S.o i387/s_ceill.S.o i387/s_copysignl.S.o i387/s_floorl.S.o i387/s_llrintl.S.o i387/s_logbl.S.o i387/s_lrintl.S.o i387/s_remquol.S.o i387/s_rintl.S.o i387/s_truncl.S.o i387/fenv.c.o bsdsrc/b_exp.c.o bsdsrc/b_log.c.o bsdsrc/b_tgamma.c.o ld80/invtrig.c.o ld80/e_acoshl.c.o ld80/e_powl.c.o ld80/k_tanl.c.o ld80/s_exp2l.c.o ld80/e_atanhl.c.o ld80/e_lgammal_r.c.o ld80/e_sinhl.c.o ld80/s_asinhl.c.o ld80/s_expm1l.c.o ld80/e_coshl.c.o ld80/e_log10l.c.o ld80/e_tgammal.c.o ld80/e_expl.c.o ld80/e_log2l.c.o ld80/k_cosl.c.o ld80/s_log1pl.c.o ld80/s_tanhl.c.o ld80/e_logl.c.o ld80/k_sinl.c.o ld80/s_erfl.c.o ld80/s_nanl.c.o
gcc -shared -nostdlib -m32 -o $DEST/libm.so src/common.c.o src/e_acos.c.o src/e_acosf.c.o src/e_acosh.c.o src/e_acoshf.c.o src/e_asin.c.o src/e_asinf.c.o src/e_atan2.c.o src/e_atan2f.c.o src/e_atanh.c.o src/e_atanhf.c.o src/e_cosh.c.o src/e_coshf.c.o src/e_expf.c.o src/e_fmodf.c.o src/e_hypot.c.o src/e_hypotf.c.o src/e_j0.c.o src/e_j0f.c.o src/e_j1.c.o src/e_j1f.c.o src/e_jn.c.o src/e_jnf.c.o src/e_lgamma.c.o src/e_lgamma_r.c.o src/e_lgammaf.c.o src/e_lgammaf_r.c.o src/e_log2.c.o src/e_log2f.c.o src/e_pow.c.o src/e_powf.c.o src/e_rem_pio2.c.o src/e_rem_pio2f.c.o src/e_sinh.c.o src/e_sinhf.c.o src/k_cos.c.o src/k_exp.c.o src/k_expf.c.o src/k_rem_pio2.c.o src/k_sin.c.o src/k_tan.c.o src/k_cosf.c.o src/k_sinf.c.o src/k_tanf.c.o src/s_asinh.c.o src/s_asinhf.c.o src/s_atan.c.o src/s_atanf.c.o src/s_carg.c.o src/s_cargf.c.o src/s_cbrt.c.o src/s_cbrtf.c.o src/s_cos.c.o src/s_cosf.c.o src/s_csqrt.c.o src/s_csqrtf.c.o src/s_erf.c.o src/s_erff.c.o src/s_exp2.c.o src/s_exp2f.c.o src/s_expm1.c.o src/s_expm1f.c.o src/s_fabs.c.o src/s_fabsf.c.o src/s_fdim.c.o src/s_fmax.c.o src/s_fmaxf.c.o src/s_fmin.c.o src/s_fminf.c.o src/s_fpclassify.c.o src/s_frexp.c.o src/s_frexpf.c.o src/s_ilogb.c.o src/s_ilogbf.c.o src/s_isinf.c.o src/s_isfinite.c.o src/s_isnormal.c.o src/s_isnan.c.o src/s_log1p.c.o src/s_log1pf.c.o src/s_modf.c.o src/s_modff.c.o src/s_nextafter.c.o src/s_nextafterf.c.o src/s_nexttowardf.c.o src/s_round.c.o src/s_roundf.c.o src/s_scalbln.c.o src/s_signbit.c.o src/s_signgam.c.o src/s_sin.c.o src/s_sincos.c.o src/s_sinf.c.o src/s_sincosf.c.o src/s_tanf.c.o src/s_tanh.c.o src/s_tanhf.c.o src/s_tgammaf.c.o src/s_cpow.c.o src/s_cpowf.c.o src/w_cabs.c.o src/w_cabsf.c.o src/s_fma.c.o src/s_fmaf.c.o src/s_lround.c.o src/s_lroundf.c.o src/s_llround.c.o src/s_llroundf.c.o src/s_nearbyint.c.o src/s_nan.c.o src/s_fabsl.c.o src/s_modfl.c.o src/e_acosl.c.o src/e_asinl.c.o src/e_atan2l.c.o src/e_fmodl.c.o src/s_fmaxl.c.o src/s_fminl.c.o src/s_ilogbl.c.o src/e_hypotl.c.o src/e_lgammal.c.o src/s_atanl.c.o src/s_cosl.c.o src/s_cprojl.c.o src/s_csqrtl.c.o src/s_fmal.c.o src/s_frexpl.c.o src/s_nexttoward.c.o src/s_roundl.c.o src/s_lroundl.c.o src/s_llroundl.c.o src/s_cpowl.c.o src/s_cargl.c.o src/s_sinl.c.o src/s_sincosl.c.o src/s_tanl.c.o src/w_cabsl.c.o src/s_nextafterl.c.o src/polevll.c.o src/s_casinl.c.o src/s_ctanl.c.o src/s_cimagl.c.o src/s_conjl.c.o src/s_creall.c.o src/s_cacoshl.c.o src/s_catanhl.c.o src/s_casinhl.c.o src/s_catanl.c.o src/s_csinl.c.o src/s_cacosl.c.o src/s_cexpl.c.o src/s_csinhl.c.o src/s_ccoshl.c.o src/s_clogl.c.o src/s_ctanhl.c.o src/s_ccosl.c.o src/s_cbrtl.c.o src/s_ccosh.c.o src/s_ccoshf.c.o src/s_cexp.c.o src/s_cexpf.c.o src/s_cimag.c.o src/s_cimagf.c.o src/s_conj.c.o src/s_conjf.c.o src/s_cproj.c.o src/s_cprojf.c.o src/s_creal.c.o src/s_crealf.c.o src/s_csinh.c.o src/s_csinhf.c.o src/s_ctanh.c.o src/s_ctanhf.c.o src/s_cacos.c.o src/s_cacosf.c.o src/s_cacosh.c.o src/s_cacoshf.c.o src/s_casin.c.o src/s_casinf.c.o src/s_casinh.c.o src/s_casinhf.c.o src/s_catan.c.o src/s_catanf.c.o src/s_catanh.c.o src/s_catanhf.c.o src/s_clog.c.o src/s_clogf.c.o i387/e_exp.S.o i387/e_fmod.S.o i387/e_log.S.o i387/e_log10.S.o i387/e_remainder.S.o i387/e_sqrt.S.o i387/s_ceil.S.o i387/s_copysign.S.o i387/s_floor.S.o i387/s_llrint.S.o i387/s_logb.S.o i387/s_lrint.S.o i387/s_remquo.S.o i387/s_rint.S.o i387/s_tan.S.o i387/s_trunc.S.o i387/s_scalbn.S.o i387/s_scalbnf.S.o i387/s_scalbnl.S.o i387/e_log10f.S.o i387/e_logf.S.o i387/e_remainderf.S.o i387/e_sqrtf.S.o i387/s_ceilf.S.o i387/s_copysignf.S.o i387/s_floorf.S.o i387/s_llrintf.S.o i387/s_logbf.S.o i387/s_lrintf.S.o i387/s_remquof.S.o i387/s_rintf.S.o i387/s_truncf.S.o i387/e_remainderl.S.o i387/e_sqrtl.S.o i387/s_ceill.S.o i387/s_copysignl.S.o i387/s_floorl.S.o i387/s_llrintl.S.o i387/s_logbl.S.o i387/s_lrintl.S.o i387/s_remquol.S.o i387/s_rintl.S.o i387/s_truncl.S.o i387/fenv.c.o bsdsrc/b_exp.c.o bsdsrc/b_log.c.o bsdsrc/b_tgamma.c.o ld80/invtrig.c.o ld80/e_acoshl.c.o ld80/e_powl.c.o ld80/k_tanl.c.o ld80/s_exp2l.c.o ld80/e_atanhl.c.o ld80/e_lgammal_r.c.o ld80/e_sinhl.c.o ld80/s_asinhl.c.o ld80/s_expm1l.c.o ld80/e_coshl.c.o ld80/e_log10l.c.o ld80/e_tgammal.c.o ld80/e_expl.c.o ld80/e_log2l.c.o ld80/k_cosl.c.o ld80/s_log1pl.c.o ld80/s_tanhl.c.o ld80/e_logl.c.o ld80/k_sinl.c.o ld80/s_erfl.c.o ld80/s_nanl.c.o

for file in $(find -name "*.o"); do
    rm $file
done
